const getCountryFlag = (countryCode: string) => {
  switch (countryCode) {
    case 'ad':
      return require('../assets/flags/AD.png');
    case 'ae':
      return require('../assets/flags/AE.png');
    case 'af':
      return require('../assets/flags/AF.png');
    case 'ag':
      return require('../assets/flags/AG.png');
    case 'ai':
      return require('../assets/flags/AI.png');
    case 'al':
      return require('../assets/flags/AL.png');
    case 'am':
      return require('../assets/flags/AM.png');
    case 'an':
      return require('../assets/flags/AN.png');
    case 'ao':
      return require('../assets/flags/AO.png');
    case 'aq':
      return require('../assets/flags/AQ.png');
    case 'ar':
      return require('../assets/flags/AR.png');
    case 'as':
      return require('../assets/flags/AS.png');
    case 'at':
      return require('../assets/flags/AT.png');
    case 'au':
      return require('../assets/flags/AU.png');
    case 'aw':
      return require('../assets/flags/AW.png');
    case 'ax':
      return require('../assets/flags/AX.png');
    case 'az':
      return require('../assets/flags/AZ.png');
    case 'ba':
      return require('../assets/flags/BA.png');
    case 'bb':
      return require('../assets/flags/BB.png');
    case 'bd':
      return require('../assets/flags/BD.png');
    case 'be':
      return require('../assets/flags/BE.png');
    case 'bf':
      return require('../assets/flags/BF.png');
    case 'bg':
      return require('../assets/flags/BG.png');
    case 'bh':
      return require('../assets/flags/BH.png');
    case 'bi':
      return require('../assets/flags/BI.png');
    case 'bj':
      return require('../assets/flags/BJ.png');
    case 'bl':
      return require('../assets/flags/BL.png');
    case 'bm':
      return require('../assets/flags/BM.png');
    case 'bn':
      return require('../assets/flags/BN.png');
    case 'bo':
      return require('../assets/flags/BO.png');
    case 'br':
      return require('../assets/flags/BR.png');
    case 'bs':
      return require('../assets/flags/BS.png');
    case 'bt':
      return require('../assets/flags/BT.png');
    case 'bw':
      return require('../assets/flags/BW.png');
    case 'by':
      return require('../assets/flags/BY.png');
    case 'bz':
      return require('../assets/flags/BZ.png');
    case 'ca':
      return require('../assets/flags/CA.png');
    case 'cc':
      return require('../assets/flags/CC.png');
    case 'cd':
      return require('../assets/flags/CD.png');
    case 'cf':
      return require('../assets/flags/CF.png');
    case 'cg':
      return require('../assets/flags/CG.png');
    case 'ch':
      return require('../assets/flags/CH.png');
    case 'ci':
      return require('../assets/flags/CI.png');
    case 'ck':
      return require('../assets/flags/CK.png');
    case 'cl':
      return require('../assets/flags/CL.png');
    case 'cm':
      return require('../assets/flags/CM.png');
    case 'cn':
      return require('../assets/flags/CN.png');
    case 'co':
      return require('../assets/flags/CO.png');
    case 'cr':
      return require('../assets/flags/CR.png');
    case 'cu':
      return require('../assets/flags/CU.png');
    case 'cv':
      return require('../assets/flags/CV.png');
    case 'cw':
      return require('../assets/flags/CW.png');
    case 'cx':
      return require('../assets/flags/CX.png');
    case 'cy':
      return require('../assets/flags/CY.png');
    case 'cz':
      return require('../assets/flags/CZ.png');
    case 'de':
      return require('../assets/flags/DE.png');
    case 'dj':
      return require('../assets/flags/DJ.png');
    case 'dk':
      return require('../assets/flags/DK.png');
    case 'dm':
      return require('../assets/flags/DM.png');
    case 'do':
      return require('../assets/flags/DO.png');
    case 'dz':
      return require('../assets/flags/DZ.png');
    case 'ec':
      return require('../assets/flags/EC.png');
    case 'ee':
      return require('../assets/flags/EE.png');
    case 'eg':
      return require('../assets/flags/EG.png');
    case 'eh':
      return require('../assets/flags/EH.png');
    case 'er':
      return require('../assets/flags/ER.png');
    case 'es':
      return require('../assets/flags/ES.png');
    case 'et':
      return require('../assets/flags/ET.png');
    case 'eu':
      return require('../assets/flags/EU.png');
    case 'fi':
      return require('../assets/flags/FI.png');
    case 'fj':
      return require('../assets/flags/FJ.png');
    case 'fk':
      return require('../assets/flags/FK.png');
    case 'fm':
      return require('../assets/flags/FM.png');
    case 'fo':
      return require('../assets/flags/FO.png');
    case 'fr':
      return require('../assets/flags/FR.png');
    case 'ga':
      return require('../assets/flags/GA.png');
    case 'gb':
      return require('../assets/flags/GB.png');
    case 'gd':
      return require('../assets/flags/GD.png');
    case 'ge':
      return require('../assets/flags/GE.png');
    case 'gg':
      return require('../assets/flags/GG.png');
    case 'gh':
      return require('../assets/flags/GH.png');
    case 'gi':
      return require('../assets/flags/GI.png');
    case 'gl':
      return require('../assets/flags/GL.png');
    case 'gm':
      return require('../assets/flags/GM.png');
    case 'gn':
      return require('../assets/flags/GN.png');
    case '':
      return require('../assets/flags/GQ.png');
    case 'gr':
      return require('../assets/flags/GR.png');
    case 'gs':
      return require('../assets/flags/GS.png');
    case 'gt':
      return require('../assets/flags/GT.png');
    case 'gu':
      return require('../assets/flags/GU.png');
    case 'gw':
      return require('../assets/flags/GW.png');
    case 'gy':
      return require('../assets/flags/GY.png');
    case 'hk':
      return require('../assets/flags/HK.png');
    case 'hn':
      return require('../assets/flags/HN.png');
    case 'hr':
      return require('../assets/flags/HR.png');
    case 'ht':
      return require('../assets/flags/HT.png');
    case 'hu':
      return require('../assets/flags/HU.png');
    case 'ic':
      return require('../assets/flags/IC.png');
    case 'id':
      return require('../assets/flags/ID.png');
    case 'ie':
      return require('../assets/flags/IE.png');
    case 'il':
      return require('../assets/flags/IL.png');
    case 'im':
      return require('../assets/flags/IM.png');
    case 'in':
      return require('../assets/flags/IN.png');
    case 'iq':
      return require('../assets/flags/IQ.png');
    case 'ir':
      return require('../assets/flags/IR.png');
    case 'is':
      return require('../assets/flags/IS.png');
    case 'it':
      return require('../assets/flags/IT.png');
    case 'je':
      return require('../assets/flags/JE.png');
    case 'jm':
      return require('../assets/flags/JM.png');
    case 'jo':
      return require('../assets/flags/JO.png');
    case 'jp':
      return require('../assets/flags/JP.png');
    case 'ke':
      return require('../assets/flags/KE.png');
    case 'kg':
      return require('../assets/flags/KG.png');
    case 'kh':
      return require('../assets/flags/KH.png');
    case 'ki':
      return require('../assets/flags/KI.png');
    case 'km':
      return require('../assets/flags/KM.png');
    case 'kn':
      return require('../assets/flags/KN.png');
    case 'kp':
      return require('../assets/flags/KP.png');
    case 'kr':
      return require('../assets/flags/KR.png');
    case 'kw':
      return require('../assets/flags/KW.png');
    case 'ky':
      return require('../assets/flags/KY.png');
    case 'kz':
      return require('../assets/flags/KZ.png');
    case 'la':
      return require('../assets/flags/LA.png');
    case 'lb':
      return require('../assets/flags/LB.png');
    case 'lc':
      return require('../assets/flags/LC.png');
    case 'li':
      return require('../assets/flags/LI.png');
    case 'lk':
      return require('../assets/flags/LK.png');
    case 'lr':
      return require('../assets/flags/LR.png');
    case 'ls':
      return require('../assets/flags/LS.png');
    case 'lt':
      return require('../assets/flags/LT.png');
    case 'lu':
      return require('../assets/flags/LU.png');
    case 'lv':
      return require('../assets/flags/LV.png');
    case 'ly':
      return require('../assets/flags/LY.png');
    case 'ma':
      return require('../assets/flags/MA.png');
    case 'mc':
      return require('../assets/flags/MC.png');
    case 'md':
      return require('../assets/flags/MD.png');
    case 'me':
      return require('../assets/flags/ME.png');
    case 'mf':
      return require('../assets/flags/MF.png');
    case 'mg':
      return require('../assets/flags/MG.png');
    case 'mh':
      return require('../assets/flags/MH.png');
    case 'mk':
      return require('../assets/flags/MK.png');
    case 'ml':
      return require('../assets/flags/ML.png');
    case 'mm':
      return require('../assets/flags/MM.png');
    case 'mn':
      return require('../assets/flags/MN.png');
    case 'mo':
      return require('../assets/flags/MO.png');
    case 'mp':
      return require('../assets/flags/MP.png');
    case 'mq':
      return require('../assets/flags/MQ.png');
    case 'mr':
      return require('../assets/flags/MR.png');
    case 'ms':
      return require('../assets/flags/MS.png');
    case 'mt':
      return require('../assets/flags/MT.png');
    case 'mu':
      return require('../assets/flags/MU.png');
    case 'mw':
      return require('../assets/flags/MW.png');
    case 'mx':
      return require('../assets/flags/MX.png');
    case 'my':
      return require('../assets/flags/MY.png');
    case 'mz':
      return require('../assets/flags/MZ.png');
    case 'na':
      return require('../assets/flags/NA.png');
    case 'nc':
      return require('../assets/flags/NC.png');
    case 'ne':
      return require('../assets/flags/NE.png');
    case 'nf':
      return require('../assets/flags/NF.png');
    case 'ng':
      return require('../assets/flags/NG.png');
    case 'ni':
      return require('../assets/flags/NI.png');
    case 'nl':
      return require('../assets/flags/NL.png');
    case 'no':
      return require('../assets/flags/NO.png');
    case 'np':
      return require('../assets/flags/NP.png');
    case 'nr':
      return require('../assets/flags/NR.png');
    case 'nu':
      return require('../assets/flags/NU.png');
    case 'nz':
      return require('../assets/flags/NZ.png');
    case 'om':
      return require('../assets/flags/OM.png');
    case 'pa':
      return require('../assets/flags/PA.png');
    case 'pe':
      return require('../assets/flags/PE.png');
    case 'pf':
      return require('../assets/flags/PF.png');
    case 'pg':
      return require('../assets/flags/PG.png');
    case 'ph':
      return require('../assets/flags/PH.png');
    case 'pk':
      return require('../assets/flags/PK.png');
    case 'pl':
      return require('../assets/flags/PL.png');
    case 'pn':
      return require('../assets/flags/PN.png');
    case 'pr':
      return require('../assets/flags/PR.png');
    case 'ps':
      return require('../assets/flags/PS.png');
    case 'pt':
      return require('../assets/flags/PT.png');
    case 'pw':
      return require('../assets/flags/PW.png');
    case 'py':
      return require('../assets/flags/PY.png');
    case 'qa':
      return require('../assets/flags/QA.png');
    case 'ro':
      return require('../assets/flags/RO.png');
    case 'ru':
      return require('../assets/flags/RU.png');
    case 'rw':
      return require('../assets/flags/RW.png');
    case 'sa':
      return require('../assets/flags/SA.png');
    case 'sb':
      return require('../assets/flags/SB.png');
    case 'sc':
      return require('../assets/flags/SC.png');
    case 'sd':
      return require('../assets/flags/SD.png');
    case 'se':
      return require('../assets/flags/SE.png');
    case 'sg':
      return require('../assets/flags/SG.png');
    case 'sh':
      return require('../assets/flags/SH.png');
    case 'si':
      return require('../assets/flags/SI.png');
    case 'sk':
      return require('../assets/flags/SK.png');
    case 'sl':
      return require('../assets/flags/SL.png');
    case 'sm':
      return require('../assets/flags/SM.png');
    case 'sn':
      return require('../assets/flags/SN.png');
    case 'so':
      return require('../assets/flags/SO.png');
    case 'sr':
      return require('../assets/flags/SR.png');
    case 'ss':
      return require('../assets/flags/SS.png');
    case 'st':
      return require('../assets/flags/ST.png');
    case 'sv':
      return require('../assets/flags/SV.png');
    case 'sy':
      return require('../assets/flags/SY.png');
    case 'sz':
      return require('../assets/flags/SZ.png');
    case 'tc':
      return require('../assets/flags/TC.png');
    case 'td':
      return require('../assets/flags/TD.png');
    case 'tf':
      return require('../assets/flags/TF.png');
    case 'tg':
      return require('../assets/flags/TG.png');
    case 'th':
      return require('../assets/flags/TH.png');
    case 'tj':
      return require('../assets/flags/TJ.png');
    case 'tl':
      return require('../assets/flags/TL.png');
    case 'tm':
      return require('../assets/flags/TM.png');
    case 'tn':
      return require('../assets/flags/TN.png');
    case 'to':
      return require('../assets/flags/TO.png');
    case 'tr':
      return require('../assets/flags/TR.png');
    case 'tt':
      return require('../assets/flags/TT.png');
    case 'tv':
      return require('../assets/flags/TV.png');
    case 'tw':
      return require('../assets/flags/TW.png');
    case 'tz':
      return require('../assets/flags/TZ.png');
    case 'ua':
      return require('../assets/flags/UA.png');
    case 'ug':
      return require('../assets/flags/UG.png');
    case 'us':
      return require('../assets/flags/US.png');
    case 'uy':
      return require('../assets/flags/UY.png');
    case 'uz':
      return require('../assets/flags/UZ.png');
    case 'va':
      return require('../assets/flags/VA.png');
    case 'vc':
      return require('../assets/flags/VC.png');
    case 've':
      return require('../assets/flags/VE.png');
    case 'vg':
      return require('../assets/flags/VG.png');
    case 'vi':
      return require('../assets/flags/VI.png');
    case 'vn':
      return require('../assets/flags/VN.png');
    case 'vu':
      return require('../assets/flags/VU.png');
    case 'wf':
      return require('../assets/flags/WF.png');
    case 'ws':
      return require('../assets/flags/WS.png');
    case 'ye':
      return require('../assets/flags/YE.png');
    case 'yt':
      return require('../assets/flags/YT.png');
    case 'za':
      return require('../assets/flags/ZA.png');
    case 'zm':
      return require('../assets/flags/ZM.png');
    case 'zw':
      return require('../assets/flags/ZW.png');
    default:
      return null;
  }
};

export const Flags = {
  getCountryFlag,
};
